### ISSUE TITLE
Plugin is not loaded with PlugmanX

### ISSUE THREAD

**Issue by lackooka** [Jsinco/BreweryX#27]
Hi, I want to uptade BreweryX and Recpies addon and I get this error message:

java.lang.IllegalStateException: Duplicate recipe ignored with ID breweryx:sealingtable
        at net.minecraft.world.item.crafting.RecipeManager.addRecipe(RecipeManager.java:91) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at org.bukkit.craftbukkit.inventory.CraftShapedRecipe.addToCraftingManager(CraftShapedRecipe.java:56) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at org.bukkit.craftbukkit.CraftServer.addRecipe(CraftServer.java:1619) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at org.bukkit.craftbukkit.CraftServer.addRecipe(CraftServer.java:1585) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at BreweryX-3.2.5-1724500277302.jar/com.dre.brewery.BSealer.registerRecipe(BSealer.java:155) ~[BreweryX-3.2.5-1724500277302.jar:?]
        at BreweryX-3.2.5-1724500277302.jar/com.dre.brewery.filedata.BConfig.readConfig(BConfig.java:381) ~[BreweryX-3.2.5-1724500277302.jar:?]
        at BreweryX-3.2.5-1724500277302.jar/com.dre.brewery.BreweryPlugin.onEnable(BreweryPlugin.java:131) ~[BreweryX-3.2.5-1724500277302.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at PlugManX-2.4.1.jar/com.rylinaux.plugman.pluginmanager.PaperPluginManager.load(PaperPluginManager.java:403) ~[PlugManX-2.4.1.jar:?]
        at PlugManX-2.4.1.jar/com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[PlugManX-2.4.1.jar:?]
        at PlugManX-2.4.1.jar/com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:94) ~[PlugManX-2.4.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2226) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2200) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1549) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1664) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1333) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Jsinco** [comment]
Always restart your server when updating BreweryX or other plugins. This is not an issue for us to fix.
