### ISSUE TITLE
Error on open new loot chest

### ISSUE THREAD

**Issue by Barlaf** [Jsinco/BreweryX#28]
Hello !
I've BreweryX in version 3.2.6 (Same probleme with 3.2.0-SNAPSHOT) with Spigot 1.20.4, and when i open a new generate chest (or barrel), i've this error:
```yml
23:17:33 ERROR]: Could not pass event LootGenerateEvent to BreweryX v3.2.6
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:322) ~[?:?]
        at java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:453) ~[?:?]
        at kotlin.random.AbstractPlatformRandom.nextInt(PlatformRandom.kt:42) ~[?:?]
        at kotlin.random.Random$Default.nextInt(Random.kt:283) ~[?:?]
        at dev.jsinco.recipes.listeners.Events.onLootGenerate(Events.kt:58) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor920.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[?:git-UniverseSpigot-"3b68a31"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[?:git-UniverseSpigot-"3b68a31"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[?:git-UniverseSpigot-"3b68a31"]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:76) ~[?:git-UniverseSpigot-"3b68a31"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[?:git-UniverseSpigot-"3b68a31"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[?:git-UniverseSpigot-"3b68a31"]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callLootGenerateEvent(CraftEventFactory.java:1981) ~[?:git-UniverseSpigot-"3b68a31"]
        at net.minecraft.world.level.storage.loot.LootTable.fillInventory(LootTable.java:171) ~[?:git-UniverseSpigot-"3b68a31"]
        at net.minecraft.world.level.storage.loot.LootTable.fill(LootTable.java:162) ~[?:git-UniverseSpigot-"3b68a31"]
        at net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.e_(RandomizableContainerBlockEntity.java:90) ~[?:?]
        at net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.createMenu(RandomizableContainerBlockEntity.java:161) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:1643) ~[?:?]
        at net.minecraft.world.level.block.BarrelBlock.use(BarrelBlock.java:52) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.use(BlockBehaviour.java:1340) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:581) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1954) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:git-UniverseSpigot-"3b68a31"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1474) ~[?:git-UniverseSpigot-"3b68a31"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:196) ~[?:git-UniverseSpigot-"3b68a31"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1451) ~[?:git-UniverseSpigot-"3b68a31"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1379) ~[?:git-UniverseSpigot-"3b68a31"]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:111) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1564) ~[?:git-UniverseSpigot-"3b68a31"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1234) ~[?:git-UniverseSpigot-"3b68a31"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[?:git-UniverseSpigot-"3b68a31"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by Barlaf** [comment]
Hello :)
I've already the last version but not a good config.
The problem was resolve after applied this in config.yml
```yml
# Recipes spawn in loot chests randomly throughout the world
# Disable this by setting your chance to -1
recipe-spawning:
  bound: 1 # The highest value that the random number can generate to. Ex: 100 means a random number between 0 and 100
  chance: -1 # The chance that a recipe will spawn in a loot chest
  blacklisted-recipes: [ex] # A list of recipes that will not spawn in loot chests
```
