### ISSUE TITLE
Plugin breaks at boot with duplicate key

### ISSUE THREAD

**Issue by TomLewis** [Jsinco/BreweryX#29]
`Duplicate key CraftBlock{pos=BlockPosition{x=2757, y=69, z=-2311},type=WATER_CAULDRON,data=Block{minecraft:water_cauldron}[level=3],fluid=net.minecraft.world.level.material.FluidTypeEmpty@4d48afe1} (attempted merging values com.dre.brewery.BCauldron@2faf0766 and com.dre.brewery.BCauldron@38672681)`

https://gist.github.com/TomLewis/413212bd3df6cb745412475128e01e92

**Comment by potatoru** [comment]
I have the same issue

```
[00:05:56] [Server thread/ERROR]: Error occurred while enabling BreweryX v3.2.6 (Is it up to date?)
java.lang.IllegalStateException: Duplicate key CraftBlock{pos=BlockPosition{x=5260, y=127, z=-2261},type=WATER_CAULDRON,data=Block{minecraft:water_cauldron}[level=3],fluid=net.minecraft.world.level.material.FluidTypeEmpty@7fe5e44c} (attempted merging values com.dre.brewery.BCauldron@136886fd and com.dre.brewery.BCauldron@ffaf467)
	at java.util.stream.Collectors.duplicateKeyException(Collectors.java:135) ~[?:?]
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at com.dre.brewery.BreweryPlugin.onEnable(BreweryPlugin.java:159) ~[BreweryX-3.2.6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2175]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2175]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2175]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2175]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2175]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2175]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2175]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2175]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2175]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by potatoru** [comment]
> @potatoru Did you update to the latest version of the plugin? that fixed it for me

Yes it loaded! I missed the update somehow. My bad
